### ISSUE TITLE
Error when building the WGT file

### ISSUE THREAD

**Issue by GreenAndBlueG** [jellyfin/jellyfin-tizen#101]
I'm having issues when i try to run the command to build the WGT file. The output of the command is this:
```
$ tizen package -t wgt -o . -- .buildResult
The active profile is used for signing. If you want to sign with other profile, please use '--sign' option.
An error has occurred. See the log file tizen-sdk/tools/ide/cli.log.
```

The log file says only that "the password is invalid"
```
2022-01-21 16:06:16,618 [TRACE] Main.java(133) - Start running Tizen CLI Main class...
2022-01-21 16:06:16,623 [TRACE] Main.java(134) - Argument count:9
2022-01-21 16:06:16,651 [TRACE] PackageCLI.java(1244) - Execute PackageCLI...
2022-01-21 16:06:16,651 [TRACE] PackageCLI.java(1246) - getRealWorkingPath: /home/gabg/jellyfin-tizen/.buildResult
2022-01-21 16:06:17,277 [ERROR] AbstractCLI.java(93) - org.tizen.common.sign.exception.CertificationException: Invaild password
java.lang.IllegalStateException: org.tizen.common.sign.exception.CertificationException: Invaild password
        at org.tizen.common.core.command.policy.UncaughtExceptionHandlingPolicy.uncaughtException(UncaughtExceptionHandlingPolicy.java:84)
        at org.tizen.common.core.command.Executor.execute(Executor.java:179)
        at org.tizen.common.core.command.Executor.execute(Executor.java:150)
        at org.tizen.ncli.subcommands.sign.SignCLICommand.getSigningProfile(SignCLICommand.java:139)
        at org.tizen.ncli.subcommands.sign.SignCLICommand.call(SignCLICommand.java:73)
        at org.tizen.ncli.subcommands.sign.SignCLICommand.call(SignCLICommand.java:58)
        at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
        at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:177)
        at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:77)
        at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
        at org.tizen.ncli.ide.shell.PackageCLI.doPackageForWgt(PackageCLI.java:903)
        at org.tizen.ncli.ide.shell.PackageCLI.execute(PackageCLI.java:1319)
        at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:189)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:122)
Caused by: org.tizen.common.sign.exception.CertificationException: Invaild password
        at org.tizen.common.sign.command.ReadSigningProfileFileCommand.checkPkcs12Password(ReadSigningProfileFileCommand.java:131)
        at org.tizen.common.sign.command.ReadSigningProfileFileCommand.validateSigningInfo(ReadSigningProfileFileCommand.java:146)
        at org.tizen.common.sign.command.ReadSigningProfileFileCommand.run(ReadSigningProfileFileCommand.java:101)
        at org.tizen.common.core.command.Executor.execute(Executor.java:164)
        ... 13 more
2022-01-21 16:06:17,284 [ERROR] Main.java(197) - org.tizen.common.sign.exception.CertificationException: Invaild password
```

I'm running this on Debian 10 Buster VM (with the `main` repo of `stretch` added)

The certificate profile that i want to use is selected in the certificate manager
![Istantanea_2022-01-21_16-13-44](https://user-images.githubusercontent.com/62039938/150551555-03015dff-1c63-4d58-8076-c11f9fa6e97b.png)

I also want to point out that this is my absolutely first time building an application of the Tizen OS, so maybe i'm just screwing up the most stupid thing :)

**Comment by GreenAndBlueG** [comment]
I've installed the latest LTS of Kubuntu in another VM, installed the `gnome-keyring` package but the situation is identical: when i try to build the WGT i get this
```
$ tizen package -t wgt -o . -- .buildResult
The active profile is used for signing. If you want to sign with other profile, please use '--sign' option.
An error has occurred. See the log file tizen-sdk/tools/ide/cli.log.
```
and the in the logs
```
2022-01-22 21:57:33,062 [TRACE] Main.java(133) - Start running Tizen CLI Main class...
2022-01-22 21:57:33,064 [TRACE] Main.java(134) - Argument count:9
2022-01-22 21:57:33,079 [TRACE] PackageCLI.java(1244) - Execute PackageCLI...
2022-01-22 21:57:33,079 [TRACE] PackageCLI.java(1246) - getRealWorkingPath: /home/gabg/jellyfin-tizen/.buildResult
2022-01-22 21:57:33,450 [ERROR] AbstractCLI.java(93) - org.tizen.common.sign.exception.CertificationException: Invaild password
java.lang.IllegalStateException: org.tizen.common.sign.exception.CertificationException: Invaild password
	at org.tizen.common.core.command.policy.UncaughtExceptionHandlingPolicy.uncaughtException(UncaughtExceptionHandlingPolicy.java:84)
	at org.tizen.common.core.command.Executor.execute(Executor.java:179)
	at org.tizen.common.core.command.Executor.execute(Executor.java:150)
	at org.tizen.ncli.subcommands.sign.SignCLICommand.getSigningProfile(SignCLICommand.java:139)
	at org.tizen.ncli.subcommands.sign.SignCLICommand.call(SignCLICommand.java:73)
	at org.tizen.ncli.subcommands.sign.SignCLICommand.call(SignCLICommand.java:58)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:177)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:77)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.ide.shell.PackageCLI.doPackageForWgt(PackageCLI.java:903)
	at org.tizen.ncli.ide.shell.PackageCLI.execute(PackageCLI.java:1319)
	at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
	at org.tizen.ncli.ide.shell.Main.run(Main.java:189)
	at org.tizen.ncli.ide.shell.Main.main(Main.java:122)
Caused by: org.tizen.common.sign.exception.CertificationException: Invaild password
	at org.tizen.common.sign.command.ReadSigningProfileFileCommand.checkPkcs12Password(ReadSigningProfileFileCommand.java:131)
	at org.tizen.common.sign.command.ReadSigningProfileFileCommand.validateSigningInfo(ReadSigningProfileFileCommand.java:146)
	at org.tizen.common.sign.command.ReadSigningProfileFileCommand.run(ReadSigningProfileFileCommand.java:101)
	at org.tizen.common.core.command.Executor.execute(Executor.java:164)
	... 13 more
2022-01-22 21:57:33,452 [ERROR] Main.java(197) - org.tizen.common.sign.exception.CertificationException: Invaild password
```

**Comment by dmitrylyzo** [comment]
> I've installed the latest LTS of Kubuntu in another VM

Going VM way, you could install Ubuntu (it is Gnome). :man_shrugging: 

You probably need to unlock the keyring.
I run Tizen under another user and thought I had to launch `SeaHorse` every time because of this.
But it looks like you (and I) need to open a keyring even under a normal user.
https://stackoverflow.com/a/61718469

**Comment by GreenAndBlueG** [comment]
Thanks a lot, it worked! :smile:
