### ISSUE TITLE
Error building WGT...again (sorry)

### ISSUE THREAD

**Issue by mariospicross** [jellyfin/jellyfin-tizen#216]
Sorry for the 2nd issue lol, I closed it expecting to have no problems with the next step. Anywho, using the excat same directory as used in the first command is telling me this time that the directry isn't valid. I'm very confused.

```
orchid@mint-server:~/jellyfin-tizen$ /home/orchid/tizen-studio/tools/ide/bin/tizen package -t wgt -o . -- .buildResult
The active profile is used for signing. If you want to sign with other profile, please use '--sign' option.
An error has occurred. See the log file tizen-studio-data/cli/logs/cli.log.
orchid@mint-server:~/jellyfin-tizen$ cat ~/tizen-studio-data/cli/logs/cli.log 
2023-08-15 21:19:39,256 [TRACE] Main.java(133) - Start running Tizen CLI Main class...
2023-08-15 21:19:39,264 [TRACE] Main.java(134) - Argument count:0
2023-08-15 21:19:39,300 [TRACE] Main.java(145) - key:metaVar_keyValue, value:<key>=<value>
2023-08-15 21:19:39,300 [TRACE] Main.java(145) - key:usage_ConfigSetting, value:Setting Tizen CLI config with given key=value pair
2023-08-15 21:20:13,593 [TRACE] Main.java(133) - Start running Tizen CLI Main class...
2023-08-15 21:20:13,599 [TRACE] Main.java(134) - Argument count:15
2023-08-15 21:20:13,743 [TRACE] BuildWebCLI.java(69) - Execute BuildWebCLI...
2023-08-15 21:20:13,860 [TRACE] BuildWebCLI.java(72) - getRealWorkingPath:/home/orchid/tizen-studio/tools/ide/bin
2023-08-15 21:20:13,933 [ERROR] AbstractCLI.java(93) - java.lang.Exception: The specified directory(/home/orchid/tizen-studio/tools/ide/bin) is not vaild
org.tizen.ncli.exceptions.UnexpectedException: java.lang.Exception: The specified directory(/home/orchid/tizen-studio/tools/ide/bin) is not vaild
	at org.tizen.ncli.subcommands.build.buildweb.BuildWebCLICommand.call(BuildWebCLICommand.java:102)
	at org.tizen.ncli.subcommands.build.buildweb.BuildWebCLICommand.call(BuildWebCLICommand.java:52)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.ide.shell.BuildWebCLI.execute(BuildWebCLI.java:86)
	at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
	at org.tizen.ncli.ide.shell.Main.run(Main.java:189)
	at org.tizen.ncli.ide.shell.Main.main(Main.java:122)
2023-08-15 21:22:34,208 [TRACE] Main.java(133) - Start running Tizen CLI Main class...
2023-08-15 21:22:34,214 [TRACE] Main.java(134) - Argument count:15
2023-08-15 21:22:34,251 [TRACE] BuildWebCLI.java(69) - Execute BuildWebCLI...
2023-08-15 21:22:34,265 [TRACE] BuildWebCLI.java(72) - getRealWorkingPath:/home/orchid/tizen-studio/tools/ide/bin
2023-08-15 21:22:34,286 [ERROR] AbstractCLI.java(93) - java.lang.Exception: The specified directory(/home/orchid/tizen-studio/tools/ide/bin) is not vaild
org.tizen.ncli.exceptions.UnexpectedException: java.lang.Exception: The specified directory(/home/orchid/tizen-studio/tools/ide/bin) is not vaild
	at org.tizen.ncli.subcommands.build.buildweb.BuildWebCLICommand.call(BuildWebCLICommand.java:102)
	at org.tizen.ncli.subcommands.build.buildweb.BuildWebCLICommand.call(BuildWebCLICommand.java:52)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.ide.shell.BuildWebCLI.execute(BuildWebCLI.java:86)
	at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
	at org.tizen.ncli.ide.shell.Main.run(Main.java:189)
	at org.tizen.ncli.ide.shell.Main.main(Main.java:122)
2023-08-15 21:25:22,170 [TRACE] Main.java(133) - Start running Tizen CLI Main class...
2023-08-15 21:25:22,179 [TRACE] Main.java(134) - Argument count:15
2023-08-15 21:25:22,222 [TRACE] BuildWebCLI.java(69) - Execute BuildWebCLI...
2023-08-15 21:25:22,234 [TRACE] BuildWebCLI.java(72) - getRealWorkingPath:/home/orchid/tizen-studio/tools/ide/bin
2023-08-15 21:25:22,252 [ERROR] AbstractCLI.java(93) - java.lang.Exception: The specified directory(/home/orchid/tizen-studio/tools/ide/bin) is not vaild
org.tizen.ncli.exceptions.UnexpectedException: java.lang.Exception: The specified directory(/home/orchid/tizen-studio/tools/ide/bin) is not vaild
	at org.tizen.ncli.subcommands.build.buildweb.BuildWebCLICommand.call(BuildWebCLICommand.java:102)
	at org.tizen.ncli.subcommands.build.buildweb.BuildWebCLICommand.call(BuildWebCLICommand.java:52)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.ide.shell.BuildWebCLI.execute(BuildWebCLI.java:86)
	at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
	at org.tizen.ncli.ide.shell.Main.run(Main.java:189)
	at org.tizen.ncli.ide.shell.Main.main(Main.java:122)
```

**Comment by dmitrylyzo** [comment]
`BuildWebCLI.java` is a build command run. `getRealWorkingPath` should point `/home/orchid/jellyfin-tizen`.

The package command outputs `PackageCLI.java`, and `getRealWorkingPath` should point to `/home/orchid/jellyfin-tizen/.buildResult` (the result of the build command).

Does `build-web` command generate `/home/orchid/jellyfin-tizen/.buildResult`?

**Comment by mariospicross** [comment]
Yes, it does. There's `config.xml`, `icon.png`, `index.html`, `tizen.js` and `/www`

**Comment by dmitrylyzo** [comment]
> Yes, it does. There's `config.xml`, `icon.png`, `index.html`, `tizen.js` and `/www`

:+1: 

There is probably a problem with the certificate. In Kubuntu, for example, password of distributor certificate can be lost if `gnome-keyring` package has not been installed.

If this is your case, you can try to install `gnome-keyring` package and recreate certificate.

Also, password can be placed directly in the `tizen-studio-data/profile/profiles.xml`. For Tizen distributor it is `tizenpkcs12passfordsigner`.
