### ISSUE TITLE
Tizen 2.4.0 stuck on jellyfin logo

### ISSUE THREAD

**Issue by driver768** [jellyfin/jellyfin-tizen#38]
Is it possible to get through the splash screen? Only seeing Jellyfin logo and that's all, built from the latest source.

**Comment by dmitrylyzo** [comment]
Try to revert this commit: jellyfin/jellyfin-web@ae2377a55d203c0b59b86e7ea7f42573bf3deda0
I think all old WebKit engines are affected.

**Comment by driver768** [comment]
you were right, now it works, but there are other problems, my homepage is empty, can't select any media 🤔

**Comment by dmitrylyzo** [comment]
> my homepage is empty, can't select any media

Do you see media libraries from browser on PC?
If yes, then probably the same as here https://github.com/jellyfin/jellyfin-tizen/issues/19#issuecomment-633065497

**Comment by driver768** [comment]
Almost the same problem.
On my pc browser, everything works.
My home page was empty, but I was pushing an ok button a few times on home link and suddenly it showed me one line of my content, other lines of my content didn't load.
After that now I can't select anything whit remote control as that comment states.

**Comment by driver768** [comment]
After some digging found the main problems.

Remote is not working when starting app after few times when installed.
If I want to gain remote control, need to login on my PC, select DLNA whit my tv, choose some content and it opens in my tv, then select home button and now I can control whit remote control.

About that home page, if I select favourites and after one second I select home, it shows my media, but only one line.

Subtitles don't work.

So there are main problems at the moment.

**Comment by dmitrylyzo** [comment]
On webOS 1.2 (emulator), I got custom element error elsewhere which is similar to that https://github.com/jellyfin/jellyfin-tizen/issues/19#issuecomment-633657382
Could you try this patch for jf-web. Idea is that we should prioritize some polyfills.

<details>
<summary>Patch</summary>

```diff
diff --git a/src/bundle.js b/src/bundle.js
index 41648f7c4..7e53b550e 100644
--- a/src/bundle.js
+++ b/src/bundle.js
@@ -4,6 +4,18 @@
 // Use define from require.js not webpack's define
 var _define = window.define;
 
+// webcomponents
+var webcomponents = require('webcomponents.js/webcomponents-lite');
+_define('webcomponents', function() {
+    return webcomponents;
+});
+
+// core-js
+var polyfill = require('@babel/polyfill/dist/polyfill');
+_define('polyfill', function () {
+    return polyfill;
+});
+
 // document-register-element
 var docRegister = require('document-register-element');
 _define('document-register-element', function() {
@@ -84,12 +96,6 @@ _define('sortable', function() {
     return sortable;
 });
 
-// webcomponents
-var webcomponents = require('webcomponents.js/webcomponents-lite');
-_define('webcomponents', function() {
-    return webcomponents;
-});
-
 // libass-wasm
 var libassWasm = require('libass-wasm');
 _define('JavascriptSubtitlesOctopus', function() {
@@ -119,12 +125,6 @@ _define('page', function() {
     return page;
 });
 
-// core-js
-var polyfill = require('@babel/polyfill/dist/polyfill');
-_define('polyfill', function () {
-    return polyfill;
-});
-
 // domtokenlist-shim
 var classlist = require('classlist.js');
 _define('classlist-polyfill', function () {
```
</details>

**Comment by driver768** [comment]
I think this fixed those problems whit home page.
Opened and closed a few times and still works.
Sometimes that spinning circle don't stop but I can interact whit menus.

Just one question, why only My Media in home page, why I can't see latest sows or continue to watch 🤔 just curious.

**Comment by dmitrylyzo** [comment]
> Sometimes that spinning circle don't stop but I can interact whit menus.

Probably another runtime error has occurred.
So if you see "Circle of Death" on home page, then this is probably the reason why you don't see other homesections.

If you have installed full Tizen Studio with TV-Extensions-3.1.2, then you can try to debug app from IDE.
You can import WGT to have clean tree.
In case of source, you need to uncheck some files/folders: https://github.com/jellyfin/jellyfin-tizen/issues/19#issuecomment-633616422

**Comment by driver768** [comment]
Not a guru in Tizen studio, whit that emulator everything works as I guess it uses modern tizen 🤨

**Comment by dmitrylyzo** [comment]
> Not a guru in Tizen studio, whit that emulator everything works as I guess it uses modern Tizen

Yes, shipped emulator is Tizen 5.5, iirc.
To run app directly on your TV, you should first connect to it with Device Manager and select it as a target (instead of an emulator).

**Comment by AlexKalopsia** [comment]
Hi, I'm not sure if this is related but I can't seem to remotely access Jellyfin from remote. I'm stuck on the splash screen (I'm not on Tizen, but the issue sounded similar)

**Comment by dmitrylyzo** [comment]
> Hi, I'm not sure if this is related but I can't seem to remotely access Jellyfin from remote. I'm stuck on the splash screen (I'm not on Tizen, but the issue sounded similar)

Feel free to open a new issue (probably directly in https://github.com/jellyfin/jellyfin-web) as yours is not related to Tizen, has different conditions, so the reason may differ.

**Comment by phirestalker** [comment]
I don't know about OP, but device manager in Tizen Studio says my TVs are tizen 3.0 devices. Does this mean I will have to stick to the commit mentioned above, or is there an intention to fix at some point?

**Comment by dmitrylyzo** [comment]
@phirestalker, you have probably built app with `master` branch of `jellyfin-web` (_this is true if you followed the guide on the project page_). It doesn't work at the moment because `pdfjs` (_at least this one I found_) is not transpiled to ES5 (_failed to fix yet_).

You can build app with jellyfin-web 10.6.4 - just checkout `release-10.6.z` branch. Moreover, using this branch is preferred if you are using a 10.6.4 server, as the development branch isn't tested on a stable server.

**Comment by phirestalker** [comment]
> @phirestalker, you have probably built app with `master` branch of `jellyfin-web` (_this is true if you followed the guide on the project page_). It doesn't work at the moment because `pdfjs` (_at least this one I found_) is not transpiled to ES5 (_failed to fix yet_).
> 
> You can build app with jellyfin-web 10.6.4 - just checkout `release-10.6.z` branch. Moreover, using this branch is preferred if you are using a 10.6.4 server, as the development branch isn't tested on a stable server.

That was it. Thanks

**Comment by gnkidwell** [comment]
> @phirestalker, you have probably built app with `master` branch of `jellyfin-web` (_this is true if you followed the guide on the project page_). It doesn't work at the moment because `pdfjs` (_at least this one I found_) is not transpiled to ES5 (_failed to fix yet_).
> 
> You can build app with jellyfin-web 10.6.4 - just checkout `release-10.6.z` branch. Moreover, using this branch is preferred if you are using a 10.6.4 server, as the development branch isn't tested on a stable server.

I am having a similar issue, sorry if I sound naive here, I do not tend to build much on linux... Needless to say, I was able to build with the master by following the instructions, but I am running Tizen 3.0 on my TV. Same issue, stuck on the Jellyfin logo... Anyway, when I try to download the jelly-web 10.6.4 zip from release-10.6.z I cannot yarn install to build the dist directory keep getting errors. Also was not sure if there was a better way to git clone that directory, I tried 

'git clone https://github.com/jellyfin/jellyfin-web/tree/release-10.6.z'
![image](https://user-images.githubusercontent.com/71857593/100524926-efe16380-3181-11eb-830e-fa618ea32f66.png)


`gnkidwell@Athena:~/SamsungCertificate/jellyfin-web$ yarn install
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[7/8] ⠠ node-sass
[6/8] ⠠ optipng-bin
[8/8] ⠠ node-sass
[4/8] ⠠ gifsicle
warning Error running install script for optional dependency: "/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/gifsicle
Output:
⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found


    at /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/bin-build/n[7/8] ⠐ node-sass
[-/8] ⠐ waiting...
[8/8] ⠐ node-sass
[-/8] ⠐ waiting...
error /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass
Output:
Building: /usr/bin/node /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.3.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 15.3.0
gyp verb command install [ '15.3.0' ]
gyp verb install input version string "15.3.0"
gyp verb install installing version: 15.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 15.3.0
gyp verb build dir attempting to create "build" dir: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gnkidwell/.node-gyp/15.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/gnkidwell/.node-gyp/15.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/gnkidwell/.node-gyp/15.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/gnkidwell/.node-gyp/15.3.0
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:192:21)
gyp ERR! System Linux 5.8.0-29-generic
gyp ERR! command "/usr/bin/node" "/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass
gyp ERR! node -v v15.3.0
gyp ERR! node-gyp -v v3.8.0
`

**Comment by dmitrylyzo** [comment]
@gnkidwell To clone that branch run `git clone -b release-10.6.z https://github.com/jellyfin/jellyfin-web`
Or, if you already cloned `master`, run `git checkout release-10.6.z` in `jellyfin-web` directory.
As for failed build, you need to install `autoconf` package.

**Comment by gnkidwell** [comment]
> git clone -b release-10.6.z https://github.com/jellyfin/jellyfin-web

I went ahead and installed autoconf... Got a little bit further I guess, I went ahead and just ran git clone -b release-10.6.z https://github.com/jellyfin/jellyfin-web 

Below you will find the new yarn install errors...

yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[7/8] ⠈ node-sass
[-/8] ⠈ waiting...
[8/8] ⠈ node-sass
[4/8] ⠈ gifsicle
error /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass
Output:
Building: /usr/bin/node /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.3.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 15.3.0
gyp verb command install [ '15.3.0' ]
gyp verb install input version string "15.3.0"
gyp verb install installing version: 15.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 15.3.0
gyp verb build dir attempting to create "build" dir: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gnkidwell/.node-gyp/15.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/gnkidwell/.node-gyp/15.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/gnkidwell/.node-gyp/15.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/gnkidwell/.node-gyp/15.3.0
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/which/which.js:80:29)
gyp ERR! stack     at /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/which/which.js:89:16
gyp ERR! stack     at /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:192:21)
gyp ERR! System Linux 5.8.0-29-generic
gyp ERR! command "/usr/bin/node" "/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass
gyp ERR! node -v v15.3.0




warning Error running install script for optional dependency: "/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/gifsicle
Output:
⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c ./configure --disable-gifview --disable-gifdiff --prefix=\"/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/gifsicle/vendor\" --bindir=\"/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/gifsicle/vendor\"
configure: error: in `/tmp/05b019b6-e1f5-45da-afdd-1cde2ccadf38':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether make sets $(MAKE)... (cached) no
checking for gcc... no
checking for cc... no
checking for cl.exe... no

    at /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/bin-build/node_modules/execa/index.js:231:11
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Promise.all (index 0)"
info This module is OPTIONAL, you can safely ignore this error

**Comment by dmitrylyzo** [comment]
Looks like you need extra packages:
- `make`
- `gcc`

**Comment by gnkidwell** [comment]
> Looks like you need extra packages:
> 
> * `make`
> * `gcc`

Got those now, less errors :)... Sorry about having you help debug this... I do seriously appreciate it though :)

yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[7/8] ⠂ node-sass
[-/8] ⠂ waiting...
[8/8] ⠂ node-sass
[4/8] ⠂ gifsicle
error /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments: 
Directory: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass
Output:
Building: /usr/bin/node /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.3.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.18
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 15.3.0
gyp verb command install [ '15.3.0' ]
gyp verb install input version string "15.3.0"
gyp verb install installing version: 15.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 15.3.0
gyp verb build dir attempting to create "build" dir: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gnkidwell/.node-gyp/15.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/gnkidwell/.node-gyp/15.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/gnkidwell/.node-gyp/15.3.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/gnkidwell/.node-gyp/15.3.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build'
  g++ '-DNODE_GYP_MODULE_NAME=libsass' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DLIBSASS_VERSION="3.5.5"' -I/home/gnkidwell/.node-gyp/15.3.0/include/node -I/home/gnkidwell/.node-gyp/15.3.0/src -I/home/gnkidwell/.node-gyp/15.3.0/deps/openssl/config -I/home/gnkidwell/.node-gyp/15.3.0/deps/openssl/openssl/include -I/home/gnkidwell/.node-gyp/15.3.0/deps/uv/include -I/home/gnkidwell/.node-gyp/15.3.0/deps/zlib -I/home/gnkidwell/.node-gyp/15.3.0/deps/v8/include -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -std=gnu++1y -std=c++0x -fexceptions -frtti -MMD -MF ./Release/.deps/Release/obj.target/libsass/src/libsass/src/ast.o.d.raw   -c -o Release/obj.target/libsass/src/libsass/src/ast.o ../src/libsass/src/ast.cpp
make: g++: No such file or directory
make: *** [src/libsass.target.mk:160: Release/obj.target/libsass/src/libsass/src/ast.o] Error 127
make: Leaving directory '/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:277:12)
gyp ERR! System Linux 5.8.0-29-generic
gyp ERR! command "/usr/bin/node" "/home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/gnkidwell/SamsungCertificate/jellyfin-web/node_modules/node-sass
gyp ERR! node -v v15.3.0

**Comment by dmitrylyzo** [comment]
`g++`
tbh, I don't remember all the required packages that I installed - need to add them to the guide :point_up:

**Comment by gnkidwell** [comment]
> `g++`
> tbh, I don't remember all the required packages that I installed - need to add them to the guide

You are amazing sir... My laptop had a heart attack running it, lol... 
'autoconf'
'make'
'gcc'
'g++'
'gyp-cli'

yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.12: The platform "linux" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
$ gulp --production
[14:58:04] Using gulpfile ~/SamsungCertificate/jellyfin-web/gulpfile.js
[14:58:04] Starting 'default'...
[14:58:04] Starting 'clean'...
[14:58:04] Finished 'clean' after 11 ms
[14:58:04] Starting 'javascript'...
[14:58:04] Starting 'apploader'...
[14:58:04] Starting 'webpack'...
[14:58:04] Starting 'css'...
[14:58:04] Starting 'html'...
[14:58:04] Starting 'images'...
[14:58:04] Starting 'copy'...
[14:58:06] Finished 'apploader' after 2.17 s
[14:58:49] gulp-imagemin: Minified 41 images (saved 1.39 MB - 63.3%)
(node:37111) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead. (Triggered by calling processImmediate on process.)
(Use `node --trace-deprecation ...` to show where the warning was created)
[14:58:52] Finished 'copy' after 48 s
[14:58:52] Finished 'images' after 48 s
[14:58:59] Finished 'html' after 55 s
[14:59:10] Finished 'javascript' after 1.08 min
[14:59:12] Finished 'css' after 1.13 min
[14:59:20] Finished 'webpack' after 1.27 min
[14:59:20] Starting 'injectBundle'...
[14:59:20] gulp-inject 1 file into index.html.
[14:59:20] Finished 'injectBundle' after 23 ms
[14:59:20] Finished 'default' after 1.27 min
Done in 266.04s.
