### ISSUE TITLE
Possible to build this with an AMD cpu?

### ISSUE THREAD

**Issue by MeltEnvy** [jellyfin/jellyfin-tizen#61]
Building this has been such a hassle. Flashed Ubuntu because Tizen-studio doesn't run on Arch. Couldn't make it run on Ubuntu either. Ended up flashing Windows, where it ran, but after a few hours of research I'm still unable to build it, because Tizen studio won't recognize virtualization support so I can't even run the emulator. I've enabled it in bios as well as Windows, but Tizen-studio doesn't seem to support AMD virtualization because it won't recognize it, so what now?

**Comment by brennschlus** [comment]
I have Ryzen 2600 and it builds fine, but emulation doesn't work. Do you want to install jellyfin on actual tv? I can build wgt file for you, but for installing on tv you must create a Samsung certificate in Certificate Manager and "Permit to install applications" in Device Manager from Tizen Studio

**Comment by NotErikUden** [comment]
Yeah, I'd need the .wgt file because for me it won't build on Windows 10 64 Bit with an AMD CPU. I already have Samsung set up and all, however the built process seems to fail for the following reasons:

Any ideas?
`yarn install v1.22.10d ..
warning package.json: No license field
info No lockfile found.
warning jellyfin-tizen@0.1.0: No license field
[1/4] Resolving packages...
warning gulp > glob-watcher > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning gulp > glob-watcher > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning gulp > gulp-cli > matchdep > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning gulp > gulp-cli > matchdep > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning gulp-dom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning gulp-dom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning gulp-dom > jsdom > request > har-validator@5.1.5: this library is no longer supported
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ gulp
Using jellyfin-web from C:\jellyfin-tizen\node_modules\jellyfin-web\dist
[14:23:46] Using gulpfile C:\jellyfin-tizen\gulpfile.js
[14:23:46] Starting 'default'...
[14:23:46] Starting 'clean'...
[14:23:46] Finished 'clean' after 9.51 ms
[14:23:46] Starting 'copy'...
[14:23:46] Starting 'modifyIndex'...
[14:23:46] Finished 'copy' after 20 ms
[14:23:46] 'modifyIndex' errored after 22 ms
[14:23:46] Error: File not found with singular glob: C:\jellyfin-tizen\node_modules\jellyfin-web\dist/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\jellyfin-tizen\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:486:12)
    at Glob._finish (C:\jellyfin-tizen\node_modules\glob\glob.js:197:8)
    at done (C:\jellyfin-tizen\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (C:\jellyfin-tizen\node_modules\glob\glob.js:688:12)
    at C:\jellyfin-tizen\node_modules\glob\glob.js:676:10
    at Glob._stat2 (C:\jellyfin-tizen\node_modules\glob\glob.js:772:12)
    at lstatcb_ (C:\jellyfin-tizen\node_modules\glob\glob.js:764:12)
[14:23:46] 'default' errored after 37 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

**Comment by jomp16** [comment]
> Yeah, I'd need the .wgt file because for me it won't build on Windows 10 64 Bit with an AMD CPU. I already have Samsung set up and all, however the built process seems to fail for the following reasons:
> 
> Any ideas?
> 
> ```
> `yarn install v1.22.10d ..
> warning package.json: No license field
> info No lockfile found.
> warning jellyfin-tizen@0.1.0: No license field
> [1/4] Resolving packages...
> warning gulp > glob-watcher > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> warning gulp > glob-watcher > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> warning gulp > gulp-cli > matchdep > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> warning gulp > gulp-cli > matchdep > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> warning gulp-dom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> warning gulp-dom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning gulp-dom > jsdom > request > har-validator@5.1.5: this library is no longer supported
> [2/4] Fetching packages...
> info fsevents@1.2.13: The platform "win32" is incompatible with this module.
> info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> [4/4] Building fresh packages...
> success Saved lockfile.
> $ gulp
> Using jellyfin-web from C:\jellyfin-tizen\node_modules\jellyfin-web\dist
> [14:23:46] Using gulpfile C:\jellyfin-tizen\gulpfile.js
> [14:23:46] Starting 'default'...
> [14:23:46] Starting 'clean'...
> [14:23:46] Finished 'clean' after 9.51 ms
> [14:23:46] Starting 'copy'...
> [14:23:46] Starting 'modifyIndex'...
> [14:23:46] Finished 'copy' after 20 ms
> [14:23:46] 'modifyIndex' errored after 22 ms
> [14:23:46] Error: File not found with singular glob: C:\jellyfin-tizen\node_modules\jellyfin-web\dist/index.html (if this was purposeful, use `allowEmpty` option)
>     at Glob.<anonymous> (C:\jellyfin-tizen\node_modules\glob-stream\readable.js:84:17)
>     at Object.onceWrapper (events.js:422:26)
>     at Glob.emit (events.js:315:20)
>     at Glob.EventEmitter.emit (domain.js:486:12)
>     at Glob._finish (C:\jellyfin-tizen\node_modules\glob\glob.js:197:8)
>     at done (C:\jellyfin-tizen\node_modules\glob\glob.js:182:14)
>     at Glob._processSimple2 (C:\jellyfin-tizen\node_modules\glob\glob.js:688:12)
>     at C:\jellyfin-tizen\node_modules\glob\glob.js:676:10
>     at Glob._stat2 (C:\jellyfin-tizen\node_modules\glob\glob.js:772:12)
>     at lstatcb_ (C:\jellyfin-tizen\node_modules\glob\glob.js:764:12)
> [14:23:46] 'default' errored after 37 ms
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`
> ```

Either you didn’t build the jellyfin-web before building the Tizen package, or the build script won’t work at all on Windows.

---

I also run Arch Linux, with amd processor, but since the SDK only runs on Ubuntu, I installed it on a Ubuntu VM and successfully built it and installed, but I haven’t tried to emulate it.

**Comment by NotErikUden** [comment]
Well, I built jellyfin-web, "successfully" (at least the CLI told me so and also there's a C:\jellyfin-web\distro directory), however I am following the instructions for Windows, which is why it is weird that it wouldn't work on Windows. May I need a newer version of NPM or other dependencies?

So all I'd have to do is emulate Ubuntu and that's it? That sounds easy. Can I then just take the wgt file and sign it with the Tizen Manager in Windows again?

**Comment by NotErikUden** [comment]
Also, can't you just send me a .wgt file? Shouldn't the file be the same for everyone unless they wish to change certain things in the code? Couldn't that file be offered in the releases section?

**Comment by jomp16** [comment]
What’s really strange is that the Tizen build is trying to pick Jellyfin-web at 

C:\jellyfin-tizen\node_modules\jellyfin-web\dist/index.html

instead of 

C:\jellyfin-web\dist\index.html

that’s why we need to specify the directory with a environment variable, but I don’t know how to declare it on Windows (it seems that you have used set (...), but it didn’t work)...

**Comment by NotErikUden** [comment]
Oh. Hm. Makes sense. That's what I needed my developer accounts for. 

> that’s why we need to specify the directory with a environment variable, but I don’t know how to declare it on Windows (it seems that you have used set (...), but it didn’t work)...

Maybe I declared it incorrectly? Should I try setting this environment variable through PATH in Windows?

**Comment by jomp16** [comment]
> Oh. Hm. Makes sense. That's what I needed my developer accounts for.
> 
> > that’s why we need to specify the directory with a environment variable, but I don’t know how to declare it on Windows (it seems that you have used set (...), but it didn’t work)...
> 
> Maybe I declared it incorrectly? Should I try setting this environment variable through PATH in Windows?

As a workaround, you can try to edit the gulpfile.js, the following line:

`var WEB_DIR = process.env.JELLYFIN_WEB_DIR || 'node_modules/jellyfin-web/dist';`

Change it to, something like:

`var WEB_DIR = 'C:\jellyfin-web\dist';`

And do a yarn install again

**Comment by NotErikUden** [comment]
Good idea! I edited the gulpfile.js:
![image](https://user-images.githubusercontent.com/52011431/111907432-8e594380-8a55-11eb-9367-4dbe46354325.png)

However, when I then tried running `yarn install` I got the same error.
(I have not set the environment variable to something different, was I wrong to not do this?)

```
yarn install v1.22.10 yarn install
warning package.json: No license field
warning jellyfin-tizen@0.1.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
$ gulp
Using jellyfin-web from C:\jellyfin-tizen\node_modules\jellyfin-web\dist
[14:55:24] Using gulpfile C:\jellyfin-tizen\gulpfile.js
[14:55:24] Starting 'default'...
[14:55:24] Starting 'clean'...
[14:55:24] Finished 'clean' after 9.61 ms
[14:55:24] Starting 'copy'...
[14:55:24] Starting 'modifyIndex'...
[14:55:24] Finished 'copy' after 20 ms
[14:55:24] 'modifyIndex' errored after 19 ms
[14:55:24] Error: File not found with singular glob: C:\jellyfin-tizen\node_modules\jellyfin-web\dist/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\jellyfin-tizen\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:486:12)
    at Glob._finish (C:\jellyfin-tizen\node_modules\glob\glob.js:197:8)
    at done (C:\jellyfin-tizen\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (C:\jellyfin-tizen\node_modules\glob\glob.js:688:12)
    at C:\jellyfin-tizen\node_modules\glob\glob.js:676:10
    at Glob._stat2 (C:\jellyfin-tizen\node_modules\glob\glob.js:772:12)
    at lstatcb_ (C:\jellyfin-tizen\node_modules\glob\glob.js:764:12)
[14:55:24] 'default' errored after 40 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\jellyfin-tizen>
```

**Comment by NotErikUden** [comment]
Hello! Thank you very much for your suggestion, sadly it did not work as I did not specify my problem correctly.

```
yarn install v1.22.10
warning package.json: No license field
warning jellyfin-tizen@0.1.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
$ gulp
Using jellyfin-web from C:\jellyfin-tizen\node_modules\jellyfin-web\dist
[14:58:24] Using gulpfile C:\jellyfin-tizen\gulpfile.js
[14:58:24] Starting 'default'...
[14:58:24] Starting 'clean'...
[14:58:24] Finished 'clean' after 9.11 ms
[14:58:24] Starting 'copy'...
[14:58:24] Starting 'modifyIndex'...
[14:58:24] Finished 'copy' after 15 ms
[14:58:24] 'modifyIndex' errored after 17 ms
[14:58:24] Error: File not found with singular glob: C:\jellyfin-tizen\node_modules\jellyfin-web\dist/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\jellyfin-tizen\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:486:12)
    at Glob._finish (C:\jellyfin-tizen\node_modules\glob\glob.js:197:8)
    at done (C:\jellyfin-tizen\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (C:\jellyfin-tizen\node_modules\glob\glob.js:688:12)
    at C:\jellyfin-tizen\node_modules\glob\glob.js:676:10
    at Glob._stat2 (C:\jellyfin-tizen\node_modules\glob\glob.js:772:12)
    at lstatcb_ (C:\jellyfin-tizen\node_modules\glob\glob.js:764:12)
[14:58:24] 'default' errored after 30 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn install v1.22.10 yarn install
warning package.json: No license field
warning jellyfin-tizen@0.1.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
$ gulp
Using jellyfin-web from C:\jellyfin-tizen\jellyfin-webdist
[15:01:19] Using gulpfile C:\jellyfin-tizen\gulpfile.js
[15:01:19] Starting 'default'...
[15:01:19] Starting 'clean'...
[15:01:19] Finished 'clean' after 9.35 ms
[15:01:19] Starting 'copy'...
[15:01:19] Starting 'modifyIndex'...
[15:01:19] Finished 'copy' after 15 ms
[15:01:19] 'modifyIndex' errored after 17 ms
[15:01:19] Error: File not found with singular glob: C:\jellyfin-tizen\jellyfin-webdist/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\jellyfin-tizen\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:486:12)
    at Glob._finish (C:\jellyfin-tizen\node_modules\glob\glob.js:197:8)
    at done (C:\jellyfin-tizen\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (C:\jellyfin-tizen\node_modules\glob\glob.js:688:12)
    at C:\jellyfin-tizen\node_modules\glob\glob.js:676:10
    at Glob._stat2 (C:\jellyfin-tizen\node_modules\glob\glob.js:772:12)
    at lstatcb_ (C:\jellyfin-tizen\node_modules\glob\glob.js:764:12)
[15:01:19] 'default' errored after 31 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
PS C:\jellyfin-tizen>
```

The modify index didn't work as I did not specify the environment variable correctly (I said that I did, so I was wrong here). I was using PowerShell to execute this, however, PowerShell needs different commands. Namely, these:

```
cd jellyfin-tizen
$env:JELLYFIN_WEB_DIR="C:\jellyfin\jellyfin-web\dist"
yarn install
```

Which I didn't use as they were hidden as a Spoiler in the [Wiki](https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows). 

My newest problem that I opened is thereby resolved:

#70

Please check out [my issue](https://github.com/jellyfin/jellyfin-tizen/issues/70) if you encounter similar modifyIndex issues.
