### ISSUE TITLE
tizen package wrong password

### ISSUE THREAD

**Issue by schdief06** [jellyfin/jellyfin-tizen#66]
Hi,

I'm having a problem with the last step of the build procedure. When running the tizen package command I'm getting the error "wrong password". I guess the password of the certificate is missing? How can I provide it?

```
$ tizen package -t wgt -o . -- .buildResult
The active profile is used for signing. If you want to sign with other profile, please use '--sign' option.
An error has occurred. See the log file tizen-sdk/tools/ide/cli.log.
```

cli.log:
```
2021-03-02 20:39:45,452 [TRACE] Main.java(132) - Start running Tizen CLI Main class...
2021-03-02 20:39:45,455 [TRACE] Main.java(133) - Argument count:11
2021-03-02 20:39:45,482 [TRACE] PackageCLI.java(1183) - Execute PackageCLI...
2021-03-02 20:39:45,483 [TRACE] PackageCLI.java(1185) - getRealWorkingPath: /home/stefan/Schreibtisch/jellyfin-tizen/.buildResult
2021-03-02 20:39:49,009 [ERROR] AbstractCLI.java(93) - org.tizen.common.sign.exception.CertificationException: Invaild password
java.lang.IllegalStateException: org.tizen.common.sign.exception.CertificationException: Invaild password
	at org.tizen.common.core.command.policy.UncaughtExceptionHandlingPolicy.uncaughtException(UncaughtExceptionHandlingPolicy.java:84)
	at org.tizen.common.core.command.Executor.execute(Executor.java:179)
	at org.tizen.common.core.command.Executor.execute(Executor.java:150)
	at org.tizen.ncli.subcommands.sign.SignCLICommand.getSigningProfile(SignCLICommand.java:139)
	at org.tizen.ncli.subcommands.sign.SignCLICommand.call(SignCLICommand.java:73)
	at org.tizen.ncli.subcommands.sign.SignCLICommand.call(SignCLICommand.java:58)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:177)
	at org.tizen.ncli.subcommands.packages.PackageCLICommand.call(PackageCLICommand.java:77)
	at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
	at org.tizen.ncli.ide.shell.PackageCLI.doPackageForWgt(PackageCLI.java:898)
	at org.tizen.ncli.ide.shell.PackageCLI.execute(PackageCLI.java:1258)
	at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
	at org.tizen.ncli.ide.shell.Main.run(Main.java:188)
	at org.tizen.ncli.ide.shell.Main.main(Main.java:121)
Caused by: org.tizen.common.sign.exception.CertificationException: Invaild password
	at org.tizen.common.sign.command.ReadSigningProfileFileCommand.checkPkcs12Password(ReadSigningProfileFileCommand.java:131)
	at org.tizen.common.sign.command.ReadSigningProfileFileCommand.validateSigningInfo(ReadSigningProfileFileCommand.java:146)
	at org.tizen.common.sign.command.ReadSigningProfileFileCommand.run(ReadSigningProfileFileCommand.java:101)
	at org.tizen.common.core.command.Executor.execute(Executor.java:164)
	... 13 more
2021-03-02 20:39:49,012 [ERROR] Main.java(196) - org.tizen.common.sign.exception.CertificationException: Invaild password
```

Thanks for your help,
Stefan

**Comment by dmitrylyzo** [comment]
In Certificate Manager. Earlier on Kubuntu, I had to install `gnome-keyring`.

**Comment by schdief06** [comment]
@dmitrylyzo thank you. I had to enter the password in the certificate manager again...

**Comment by otahmasebi** [comment]
I think it's because of kde wallet,
I entered password manually in my tizen profile file located in `~/tizen-studio-data/profile/profiles.xml`.
It worked for me.

**Comment by zomp** [comment]
@otahmasebi whenever (and whatever) I entered there, it did not work. Even when _gnome-keyring_ was installed. Could you be please more specific (which distro/version you have, which keyrings, what steps...)?

For me, to make it work on Kubuntu 21.04, in Tizen Studio _preferences_ under _general_ → _security_ → _secure storage_ I turned off _Linux Integration_ and _UI Prompt_. Then the passwords could be written in plain text to _profiles.xml_ and _gnome-keyring_ was not necessary any more (I uninstalled it again).

**Comment by mariospicross** [comment]
worked perfectly otahmasebi ily
