### ISSUE TITLE
SyncPlay error

### ISSUE THREAD

**Issue by ilteoood** [jellyfin/jellyfin-tizen#67]
Hi,
during the creation or access of a SyncPlay group, appears a pop-up saying that there was an error retrievieng the groups lists.

The same function on the web interface is ok.

I'm using the latest docker image of jellyfin, and when this happens I see the following logs:

```
[21:42:15] [ERR] [29] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://*:8096/SyncPlay/List


System.NullReferenceException: Object reference not set to an instance of an object.


   at Emby.Server.Implementations.SyncPlay.SyncPlayController.GetPlayingItemId()


   at Emby.Server.Implementations.SyncPlay.SyncPlayManager.<>c__DisplayClass21_0.<ListGroups>b__2(ISyncPlayController group)


   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()


   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)


   at Emby.Server.Implementations.SyncPlay.SyncPlayManager.ListGroups(SessionInfo session, Guid filterItemId)


   at MediaBrowser.Api.SyncPlay.SyncPlayService.Get(SyncPlayList request)


   at lambda_method(Closure , Object , Object )


   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)


   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)


   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)


   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)


[21:42:15] [ERR] [32] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request. URL: http://*:8096/SyncPlay/List


System.NullReferenceException: Object reference not set to an instance of an object.


   at Emby.Server.Implementations.SyncPlay.SyncPlayController.GetPlayingItemId()


   at Emby.Server.Implementations.SyncPlay.SyncPlayManager.<>c__DisplayClass21_0.<ListGroups>b__2(ISyncPlayController group)


   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()


   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)


   at Emby.Server.Implementations.SyncPlay.SyncPlayManager.ListGroups(SessionInfo session, Guid filterItemId)


   at MediaBrowser.Api.SyncPlay.SyncPlayService.Get(SyncPlayList request)


   at lambda_method(Closure , Object , Object )


   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)


   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)


   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)


   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)
```

**Comment by ilteoood** [comment]
Issue related to the jellyfin rc version
