### ISSUE TITLE
error when creating wgt file

### ISSUE THREAD

**Issue by elvis0288** [jellyfin/jellyfin-tizen#7]
Hello,

thank you for all your work. this is what i am getting when trying to create the wgt

C:\jellyfin\jellyfin-tizen>tizen build-web -e ".*" -e gulpfile.js -e README.md -e "node_modules/*" -e "package*.json" -e "yarn.lock"
Tizen adapter
C:\jellyfin\jellyfin-tizen\tizen.js:14
        var deviceId = localStorage.getItem('_deviceId2');
                       ^

ReferenceError: localStorage is not defined
    at getDeviceId (C:\jellyfin\jellyfin-tizen\tizen.js:14:24)
    at C:\jellyfin\jellyfin-tizen\tizen.js:25:19
    at Object.<anonymous> (C:\jellyfin\jellyfin-tizen\tizen.js:151:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

thanks

**Comment by dmitrylyzo** [comment]
It seems that it run `tizen.js` instead of wgt build.
Since you under Windows, you need to run `tizen.bat`, iirc
[wiki/Build-on-Windows](https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows)
