### ISSUE TITLE
Can't build because of modifyIndex error. 

### ISSUE THREAD

**Issue by NotErikUden** [jellyfin/jellyfin-tizen#70]
I followed the instructions line by line to build on Windows. I am using a Windows 10 system with Git Bash installed and did the previous sections of this [Wiki ](https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Windows) within Git Bash. However, since the Jellyfin Tizen section asks for PowerShell, I began using PowerShell. 

I have an AMD Ryzen Threadripper 1920X which should be used for the build process, however, when I type "yarn install" within the C:\jellyfin-tizen\ directory (after the C:\jellyfin-web\ build finished successfully!) I get the following errors:

```
yarn install v1.22.10d ..
warning package.json: No license field
info No lockfile found.
warning jellyfin-tizen@0.1.0: No license field
[1/4] Resolving packages...
warning gulp > glob-watcher > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning gulp > glob-watcher > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning gulp > gulp-cli > matchdep > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning gulp > gulp-cli > matchdep > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning gulp-dom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning gulp-dom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning gulp-dom > jsdom > request > har-validator@5.1.5: this library is no longer supported
[2/4] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ gulp
Using jellyfin-web from C:\jellyfin-tizen\node_modules\jellyfin-web\dist
[14:23:46] Using gulpfile C:\jellyfin-tizen\gulpfile.js
[14:23:46] Starting 'default'...
[14:23:46] Starting 'clean'...
[14:23:46] Finished 'clean' after 9.51 ms
[14:23:46] Starting 'copy'...
[14:23:46] Starting 'modifyIndex'...
[14:23:46] Finished 'copy' after 20 ms
[14:23:46] 'modifyIndex' errored after 22 ms
[14:23:46] Error: File not found with singular glob: C:\jellyfin-tizen\node_modules\jellyfin-web\dist/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\jellyfin-tizen\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:486:12)
    at Glob._finish (C:\jellyfin-tizen\node_modules\glob\glob.js:197:8)
    at done (C:\jellyfin-tizen\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (C:\jellyfin-tizen\node_modules\glob\glob.js:688:12)
    at C:\jellyfin-tizen\node_modules\glob\glob.js:676:10
    at Glob._stat2 (C:\jellyfin-tizen\node_modules\glob\glob.js:772:12)
    at lstatcb_ (C:\jellyfin-tizen\node_modules\glob\glob.js:764:12)
[14:23:46] 'default' errored after 37 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

For those interested, the output of the successful jellyfin-web build looks like this:
```
PS C:\jellyfin-web> yarn install
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "webpack-dev-server > webpack-dev-middleware@3.7.2" has incorrect peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
$ node ./scripts/prepare.js
assets by chunk 27.6 MiB (auxiliary id hint: vendors) 903 assets
assets by path *.js 9.67 MiB
  assets by chunk 1.94 MiB (id hint: vendors) 12 assets
assets by path assets/ 732 KiB 43 assets
assets by path libraries/ 7.53 MiB 11 assets
assets by path themes/ 1.16 MiB 4 assets
assets by chunk 500 KiB (auxiliary name: main) 4 assets
assets by path *.svg 2.2 KiB
  asset cb6e840e08726299bf8f968fe08d7ead.svg 1.39 KiB [emitted] [immutable] [from: assets/img/fresh.svg] (auxiliary name: playback-video)
  asset 0d2b37694d352e7e4c591afc205984ff.svg 833 bytes [emitted] [immutable] [from: assets/img/rotten.svg] (auxiliary name: playback-video)
assets by path *.json 1.68 KiB
  asset config.json 905 bytes [emitted] [from: config.json] [copied]
  asset manifest.json 814 bytes [emitted] [from: manifest.json] [copied]
10 assets
orphan modules 2.11 MiB [orphan] 488 modules
runtime modules 22.6 KiB 12 modules
modules by path ../node_modules/ 5.48 MiB 1787 modules
modules by path ./ 7.7 MiB
  javascript modules 4.03 MiB
    cacheable modules 4.03 MiB 389 modules
    modules by path ./controllers/ lazy ^/.// 320 bytes 2 modules
    modules by path ./components/tvproviders/ lazy ^/.// 320 bytes 2 modules
  json modules 3.67 MiB 65 modules
canvas (ignored) 15 bytes [built] [code generated]
fs (ignored) 15 bytes [built] [code generated]
zlib (ignored) 15 bytes [optional] [built] [code generated]
http (ignored) 15 bytes [built] [code generated]
https (ignored) 15 bytes [built] [code generated]
url (ignored) 15 bytes [built] [code generated]

LOG from InjectManifest
<i> The service worker at serviceworker.js will precache
<i>         1319 URLs, totaling 46.4 MB.

WARNING in ../node_modules/epubjs/src/section.js 118:23-39
export 'XMLDOMParser' (imported as 'XMLDOMSerializer') was not found in 'xmldom' (possible exports: DOMImplementation, DOMParser, XMLSerializer)
 @ ../node_modules/epubjs/src/spine.js 14:0-32 123:24-31
 @ ../node_modules/epubjs/src/book.js 23:0-28 140:21-26
 @ ../node_modules/epubjs/src/index.js 1:0-26 8:0-54
 @ ./plugins/bookPlayer/plugin.js
 @ ./plugins/ lazy ^\.\/.*$ chunkName: [request] namespace object ./bookPlayer/plugin.js ./bookPlayer/plugin
 @ ./components/pluginManager.js 138:23-140:49
 @ ./scripts/site.js 34:0-60 141:14-27 158:13-37

WARNING in ./components/apphost.js 46:76-87
Should not import the named export 'version' (imported as '_appVersion') from default-exporting module (only default export is available soon)
 @ ./scripts/site.js

WARNING in ./components/apphost.js 380:74-85
Should not import the named export 'version' (imported as '_appVersion') from default-exporting module (only default export is available soon)
 @ ./scripts/site.js

WARNING in libraries/subtitles-octopus-worker-legacy.js is 3.01 MB, and won't be precached. Configure maximumFileSizeToCacheInBytes to change this limit.

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  themes/blueradiance/bg.jpg (933 KiB)
  libraries/subtitles-octopus-worker.js (303 KiB)
  libraries/subtitles-octopus-worker.wasm (1.85 MiB)
  libraries/subtitles-octopus-worker-legacy.js (2.87 MiB)
  libraries/subtitles-octopus-worker-legacy.js.mem (627 KiB)
  libraries/pdf.worker.js (641 KiB)
  libraries/wasm-gen/libarchive.wasm (875 KiB)
  7025.200339506325e9d6d96c.bundle.js (773 KiB)
  7084.2be5e4e37434f0e1bb10.bundle.js (605 KiB)
  main.312baff8dd35900739f0.bundle.js (967 KiB)
  9530.7bf3a1ae1c14b75a71f8.bundle.js (331 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (967 KiB)
      main.312baff8dd35900739f0.bundle.js


webpack 5.24.2 compiled with 6 warnings in 113050 ms
Done in 186.50s.
```

I set the environment variable `set JELLYFIN_WEB_DIR=C:\jellyfin\jellyfin-web\dist` exactly like this before executing the build command for jellyfin-web, any ideas on why I get an error?

**Comment by dmitrylyzo** [comment]
`Using jellyfin-web from C:\jellyfin-tizen\node_modules\jellyfin-web\dist` - environment variable `JELLYFIN_WEB_DIR` was not set.
I believe if you are using Git Bash you can follow [Linux guide](https://github.com/jellyfin/jellyfin-tizen/wiki/Build-on-Linux#prepare-interface).
```sh
JELLYFIN_WEB_DIR=/c/jellyfin/jellyfin-web/dist yarn install
```
_I may be wrong with path_

**Comment by NotErikUden** [comment]
Ahhh, thank you! I reversed an edit I made to the gulpfile to try this out. Am trying it as we speak.

**Comment by NotErikUden** [comment]
I built jellyfin-web successfully. I actually just downloaded jellyfin-web straight to my C: drive, so the command I just used was:

`JELLYFIN_WEB_DIR=/c/jellyfin-web/dist yarn install`


Thank you for the powershell command!

**Comment by NotErikUden** [comment]
I built jellyfin-web successfully. I actually just downloaded jellyfin-web straight to my C: drive, so the command I just used was:

`JELLYFIN_WEB_DIR=/c/jellyfin-web/dist yarn install`

**Comment by NotErikUden** [comment]
Ohhhh. 

```
eriku@Desktop MINGW64 /c/jellyfin-tizen (master)
$ JELLYFIN_WEB_DIR=/c/jellyfin-web/dist yarn install
yarn install v1.22.10
warning package.json: No license field
warning jellyfin-tizen@0.1.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
$ gulp
Using jellyfin-web from C:\jellyfin-web\dist
[15:05:29] Using gulpfile C:\jellyfin-tizen\gulpfile.js
[15:05:29] Starting 'default'...
[15:05:29] Starting 'clean'...
[15:05:29] Finished 'clean' after 9.85 ms
[15:05:29] Starting 'copy'...
[15:05:29] Starting 'modifyIndex'...
[15:05:29] Finished 'modifyIndex' after 232 ms
[15:05:41] Finished 'copy' after 12 s
[15:05:41] Finished 'default' after 12 s
Done in 14.25s.
```


Wonderful! I think it worked using Git Bash and your changed command/the Linux command! No gulpfile.js edit needed. Thank you so much!

**Comment by NotErikUden** [comment]
The issue was with declaring the environment variable. Do so accordingly by using the right instructions and everything will work (for anyone encountering this issue in the future).
