### ISSUE TITLE
yarn install issue on windows

### ISSUE THREAD

**Issue by jringo12** [jellyfin/jellyfin-tizen#82]
C:\jellyfin-tizen>yarn install
yarn install v1.22.10
warning package.json: No license field
warning jellyfin-tizen@0.1.0: No license field
[1/4] Resolving packages...
success Already up-to-date.
$ gulp
Using jellyfin-web from C:\jellyfin\jellyfin-web\dist
[23:41:58] Using gulpfile C:\jellyfin-tizen\gulpfile.js
[23:41:58] Starting 'default'...
[23:41:58] Starting 'clean'...
[23:41:58] Finished 'clean' after 6.79 ms
[23:41:58] Starting 'copy'...
[23:41:58] Starting 'modifyIndex'...
[23:41:58] Finished 'copy' after 11 ms
[23:41:58] 'modifyIndex' errored after 13 ms
[23:41:58] Error: File not found with singular glob: C:\jellyfin\jellyfin-web\dist/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\jellyfin-tizen\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:467:12)
    at Glob._finish (C:\jellyfin-tizen\node_modules\glob\glob.js:197:8)
    at done (C:\jellyfin-tizen\node_modules\glob\glob.js:182:14)
    at Glob._processSimple2 (C:\jellyfin-tizen\node_modules\glob\glob.js:688:12)
    at C:\jellyfin-tizen\node_modules\glob\glob.js:676:10
    at Glob._stat2 (C:\jellyfin-tizen\node_modules\glob\glob.js:772:12)
    at lstatcb_ (C:\jellyfin-tizen\node_modules\glob\glob.js:764:12)
[23:41:58] 'default' errored after 24 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by jringo12** [comment]
I had the wrong folder set. So it is all good now.
