### ISSUE TITLE
I've hit a roadblock while preparing the interface.

### ISSUE THREAD

**Issue by TheAwesomeGuy11** [jellyfin/jellyfin-tizen#89]
What do I do about this? I managed to get it onto the TV but I had to redo it because it said that the webpage was unavailable. 

`C:\Users\thomas\jellyfin-tizen>set JELLYFIN_WEB_DIR=c:\jellyfin\jellyfin-web\dist

C:\Users\thomas\jellyfin-tizen>npm install
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> jellyfin-tizen@0.1.0 postinstall C:\Users\thomas\jellyfin-tizen
> gulp

Using jellyfin-web from c:\jellyfin\jellyfin-web\dist
[15:28:06] Using gulpfile ~\jellyfin-tizen\gulpfile.js
[15:28:06] Starting 'default'...
[15:28:06] Starting 'clean'...
[15:28:06] Finished 'clean' after 13 ms
[15:28:06] Starting 'copy'...
[15:28:06] Starting 'modifyIndex'...
[15:28:06] Finished 'copy' after 21 ms
[15:28:06] 'modifyIndex' errored after 24 ms
[15:28:06] Error: File not found with singular glob: c:\jellyfin\jellyfin-web\dist/index.html (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (C:\Users\thomas\jellyfin-tizen\node_modules\glob-stream\readable.js:84:17)
    at Object.onceWrapper (events.js:422:26)
    at Glob.emit (events.js:315:20)
    at Glob.EventEmitter.emit (domain.js:467:12)
    at Glob._finish (C:\Users\thomas\jellyfin-tizen\node_modules\glob\glob.js:195:8)
    at done (C:\Users\thomas\jellyfin-tizen\node_modules\glob\glob.js:180:14)
    at Glob._processSimple2 (C:\Users\thomas\jellyfin-tizen\node_modules\glob\glob.js:686:12)
    at C:\Users\thomas\jellyfin-tizen\node_modules\glob\glob.js:674:10
    at Glob._stat2 (C:\Users\thomas\jellyfin-tizen\node_modules\glob\glob.js:770:12)
    at lstatcb_ (C:\Users\thomas\jellyfin-tizen\node_modules\glob\glob.js:762:12)
[15:28:06] 'default' errored after 41 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jellyfin-tizen@0.1.0 postinstall: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jellyfin-tizen@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\thomas\AppData\Roaming\npm-cache\_logs\2021-07-25T05_58_06_390Z-debug.log

C:\Users\thomas\jellyfin-tizen>`

**Comment by dmitrylyzo** [comment]
In the command `set JELLYFIN_WEB_DIR=c:\jellyfin\jellyfin-web\dist`, the variable should point to the folder with the compiled jellyfin-web.
Does `c:\jellyfin\jellyfin-web\dist\index.html` exist?

**Comment by TheAwesomeGuy11** [comment]
I found a solution! I copied the files from a precompiled one then signed it and put it on the tv now it works. I think it was from #1  if I recall correctly
